import { Page, expect } from '@playwright/test';
import { BasePage } from './base.page';
import { AccountOpeningLocators } from '../locators/account-opening.locators';

export type AccountType = 'CHECKING' | 'SAVINGS';

export class AccountOpeningPage extends BasePage {
  readonly locators: AccountOpeningLocators;

  constructor(page: Page) {
    super(page);
    this.locators = new AccountOpeningLocators(page);
  }

  async open(): Promise<void> {
    await this.click(this.locators.openNewAccountLink);
    await this.verifyUrl(/openaccount\.htm/, 15_000);
  }

  async openAccount(accountType = 'SAVINGS', sourceAccountId?: string): Promise<string> {
    await this.page
      .waitForLoadState('networkidle', { timeout: 10000 })
      .catch(() => undefined);
    await this.verifyVisible(this.locators.accountType, 15000);
    await this.verifyVisible(this.locators.fromAccount, 15000);
    await this.locators.accountType.selectOption({ label: accountType });

    // Opening an account requires an existing account to fund the initial deposit.
    await expect(
      this.locators.fromAccount.locator('option[value]:not([value=""])')
    ).not.toHaveCount(0, { timeout: 15000 });
    if (sourceAccountId) {
      await this.locators.fromAccount.selectOption({ value: sourceAccountId });
    } else {
      await this.locators.fromAccount.selectOption({ index: 0 });
    }
    await this.submitOpening();
    await this.verifyVisible(this.locators.accountOpenedMessage, 15_000);

    // The account ID is generated by ParaBank and changes on every run.
    const accountNumberText = (
      await this.locators.newAccountId.textContent()
    )?.trim();
    if (!accountNumberText) {
      throw new Error(
        'Account opened successfully but no account number was displayed'
      );
    }
    console.log('New account number: ' + accountNumberText);
    return accountNumberText;
  }

  async submitOpening(): Promise<void> {
    await this.locators.openAccountButton.click({ force: true });
  }

  async getSourceAccountId(): Promise<string> {
    const selectedAccountIds = await this.locators.fromAccount.selectOption({ index: 0 });
    return selectedAccountIds[0] ?? '';
  }

  async verifyOpeningError(): Promise<void> {
    await this.verifyVisible(this.locators.errorMessage, 15_000);
  }
}
